name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    if: ${{ (github.event_name == 'push' && !contains(github.event.head_commit.message, '[skip ci]')) || github.event_name == 'pull_request' }}
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Typecheck
        run: pnpm run typecheck

      - name: Test
        run: pnpm run test:coverage

      - name: Build
        run: pnpm run build

      - name: Build npm package
        run: |
          pnpm pack
          tarball=$(ls -1 *.tgz)
          mv "$tarball" pkg.tgz

      - name: Upload Test coverage to Codecov
        uses: codecov/codecov-action@v5

      - uses: actions/upload-artifact@v4
        with:
          name: npm-package
          path: pkg.tgz
