name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: [ '10', '12' ]
    name: Node ${{ matrix.node }} test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-build-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-
      - run: |
          npm -g install pnpm@5.16
          pnpm set verify-store-integrity false
      - run: pnpm install
      - run: pnpm run test:coverage
      - uses: codecov/codecov-action@v1
      - run: mv "$(pnpm pack | tail -n 1)" pkg.tgz
      - uses: actions/upload-artifact@v2
        with:
          name: package-art
          path: pkg.tgz
